# Generated by Django 5.1.6 on 2025-02-14 02:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('regulatoria', 'Regulatoria'), ('no_regulatoria', 'No Regulatoria')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrganismoSectorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('SEA', 'Servicio de Evaluación Ambiental'), ('SEC', 'Superintendencia de Electricidad y Combustible'), ('IRV', 'Intendencia Regional de Valparaíso'), ('DGTM', 'Dirección General del Territorio Marítimo y de Marina Mercante'), ('CONAF', 'Corporación Nacional Forestal'), ('SAG', 'Servicio Agrícola y Ganadero')], max_length=5, unique=True)),
                ('contacto', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedidaAvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_limite', models.DateField()),
                ('avance', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('E', 'En progreso'), ('C', 'Completado'), ('R', 'Retrasado')], default='P', max_length=1)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='reportes.medida')),
            ],
            options={
                'verbose_name': 'Medida de Avance',
                'verbose_name_plural': 'Medidas de Avance',
            },
        ),
        migrations.AddField(
            model_name='medida',
            name='organismo_responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.organismosectorial'),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PPDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('organismo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ppdas', to='reportes.organismosectorial')),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('valor', models.FloatField()),
                ('unidad', models.CharField(blank=True, max_length=50)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('medio_verificacion', models.FileField(blank=True, null=True, upload_to='medios_verificacion/')),
                ('organismo_sectorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.organismosectorial')),
                ('ppda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reportes.ppda')),
            ],
        ),
        migrations.CreateModel(
            name='AlertaCritica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_alerta', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('resuelta', 'Resuelta')], max_length=50)),
                ('organismo_sectorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.organismosectorial')),
                ('ppda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reportes.ppda')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField()),
                ('cumplimiento', models.FloatField(help_text='Porcentaje de cumplimiento')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.medidaavance')),
                ('organismo_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.organismosectorial')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteConsolidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField()),
                ('resumen_actividades', models.TextField()),
                ('archivo_reporte', models.FileField(upload_to='reportes_anuales/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('organismo_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.organismosectorial')),
                ('ppda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reportes.ppda')),
            ],
        ),
    ]
