# Generated by Django 4.2.7 on 2025-04-21 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reportes', '0002_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='organismosectorial',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='organismosectorial',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ppda',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ppda',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ppda',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='organismosectorial',
            name='nombre',
            field=models.CharField(choices=[('SEA', 'Servicio de Evaluación Ambiental'), ('SEC', 'Superintendencia de Electricidad y Combustible'), ('IRV', 'Intendencia Regional de Valparaíso'), ('DGTM', 'Dirección General del Territorio Marítimo y de Marina Mercante'), ('CONAF', 'Corporación Nacional Forestal'), ('SAG', 'Servicio Agrícola y Ganadero')], db_index=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ppda',
            name='fecha_inicio',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='ppda',
            name='fecha_termino',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='ppda',
            name='nombre',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='organismosectorial',
            index=models.Index(fields=['nombre'], name='reportes_or_nombre_ca5e1c_idx'),
        ),
        migrations.AddIndex(
            model_name='perfilusuario',
            index=models.Index(fields=['rol'], name='reportes_pe_rol_579c61_idx'),
        ),
        migrations.AddIndex(
            model_name='ppda',
            index=models.Index(fields=['nombre'], name='reportes_pp_nombre_77b573_idx'),
        ),
        migrations.AddIndex(
            model_name='ppda',
            index=models.Index(fields=['fecha_inicio', 'fecha_termino'], name='reportes_pp_fecha_i_7200b1_idx'),
        ),
    ]
